### PR TITLE
watchOS support

### PR DESCRIPTION
**Pull request by leaferiksen**
This was the first time I ever doing a `pull --rebase` and my second time making a PR, but I did eventually things working on 0.0.3.

I am sure there is a lot of work for me to do before you want to even consider merging this, but this is all I had time to pull off tonight, and I thought getting it out there was a lot better than doing nothing.

Please tell me what other info you want about this work. My assumption is that the biggest issue is that it is all one commit, but I'll wait to hear back from you before acting on that assumption.

### CODE REVIEW

**Comment by leaferiksen** [comment]
AmgiModifiersWatch.swift might not really be needed, but I added it to avoid some build issues that I haven't yet sorted through.

File: scripts/build-xcframework.sh [hunk 1]
```diff
@@ -24,21 +26,41 @@ cargo build \
     --target aarch64-apple-ios-sim \
     --release
 
+echo "==> Building for watchOS device (aarch64-apple-watchos)..."
+cargo build \
+    --manifest-path "$BRIDGE_DIR/Cargo.toml" \
+    --target aarch64-apple-watchos \
```
Comment (antigluten) [inline scripts/build-xcframework.sh]: **Tier 3 Rust target — this build will fail for the next contributor.**

`aarch64-apple-watchos` and `aarch64-apple-watchos-sim` are [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support.html) targets. A plain `cargo build --target …` won't work — they require:

- a `nightly` toolchain
- `rustup component add rust-src --toolchain nightly`
- `-Z build-std=std,panic_abort` on the cargo invocation

Otherwise: `error[E0463]: can't find crate for 'std'` / `target may not be installed`.

Suggested fix:
```bash
cargo +nightly build \
    --manifest-path "$BRIDGE_DIR/Cargo.toml" \
    --target aarch64-apple-watchos \
    -Z build-std=std,panic_abort \
    --release
```

Either bake the toolchain into the script with a clear "you need nightly + rust-src" check up front, or document the prerequisites in the README so CI/contributors aren't blocked.

File: AmgiApp/Sources/Watch/WatchDeckDetailView.swift [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+                    Label("Study", systemImage: "play.fill")
+                        .frame(maxWidth: .infinity)
+                }
+                .buttonStyle(.borderedProminent)
+                .disabled(counts.total == 0)
+                Text("Tap to replay audio, double tap to exit.")
+            }
+        }
+        .navigationTitle(deck.name.split(separator: "::").last ?? "")
+        .fullScreenCover(isPresented: $showReview) {
```
Comment (antigluten) [inline AmgiApp/Sources/Watch/WatchDeckDetailView.swift]: **`fullScreenCover` is iOS/tvOS only — not available on watchOS.**

If this is actually compiling for the watch target, it's almost certainly being resolved to a different overload or silently no-op'ing. On watchOS, replace with:

- `NavigationLink(value:) { … }` + `.navigationDestination(for:)` (preferred — fits the watch nav model), or
- `.sheet(isPresented: $showReview) { … }` if you want modal semantics.

Worth verifying on a real device — a no-op `Study` button is exactly the kind of thing that survives the simulator and breaks on hardware.

File: AmgiApp/Sources/Watch/WatchReviewView.swift [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+            Text(title).font(font).frame(maxWidth: .infinity)
+        }
+        .padding(10).buttonStyle(.plain).frame(maxWidth: .infinity).background(color)
+    }
+    private func ratingButton(_ rating: Rating, color: Color) -> some View {
+        reviewButton(session.nextIntervals[rating] ?? "", color: color, font: .caption) {
+            session.answer(rating: rating)
+        }
+    }
+    private func playAudio(from html: String) {
```
Comment (antigluten) [inline AmgiApp/Sources/Watch/WatchReviewView.swift:84]: **`AVAudioSession` is never configured — audio will likely be silent on real watch hardware.**

watchOS routes audio differently from iOS. An `AVQueuePlayer.play()` with no session setup typically produces no output (or routes to the wrong destination, e.g. paired phone). You need to set the category + activate the session before the first `play()`:

```swift
try AVAudioSession.sharedInstance().setCategory(
    .playback,
    mode: .default,
    policy: .longFormAudio
)
// activate(options:) is async on watchOS — await it once at launch, not per tap.
try await AVAudioSession.sharedInstance().activate(options: [])
```

Do this once at app start (or first review), not on every `playAudio` call.

File: AmgiApp/Sources/Watch/WatchReviewView.swift [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+                }
+                .ignoresSafeArea(edges: .bottom)
+            }
+        }
+        .background(Color.black)
+        ._statusBarHidden()
+        .toolbar(.hidden, for: .navigationBar)
+        .ignoresSafeArea(edges: .top)
+        .onTapGesture { playAudio(from: session.showAnswer ? session.backHTML : session.frontHTML) }
+        .onTapGesture(count: 2) { dismiss() }
```
Comment (antigluten) [inline AmgiApp/Sources/Watch/WatchReviewView.swift:46]: **Single-tap + double-tap on the same view fight each other.**

SwiftUI doesn't reliably disambiguate stacked `.onTapGesture` modifiers — every double tap also fires the single-tap handler (replaying audio), and the single-tap is delivered with a delay so you feel the lag. The hint "Tap to replay audio, double tap to exit" in the parent view reads like a workaround for exactly this.

Better options on watchOS:
- Use the digital crown or a dedicated `Button` for "exit"
- Use `SimultaneousGesture`/`ExclusiveGesture` to compose them with explicit precedence
- Move "replay audio" off tap entirely (e.g. swipe, or auto-replay on showAnswer change which you already do on line 49)

File: AmgiApp/Sources/Watch/WatchReviewView.swift [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+            return AVPlayerItem(url: URL(fileURLWithPath: mediaDir).appendingPathComponent(String(html[range])))
+        }
+        audioPlayer.removeAllItems()
+        items.forEach { if audioPlayer.canInsert($0, after: nil) { audioPlayer.insert($0, after: nil) } }
+        audioPlayer.play()
+    }
+}
+extension String {
+    fileprivate var stripped: String {
+        self.replacingOccurrences(of: "(?s)<style.*?>.*?</style>", with: "", options: .regularExpression)
```
Comment (antigluten) [inline AmgiApp/Sources/Watch/WatchReviewView.swift:100]: **Inline `(?s)` modifier is unreliable through `NSRegularExpression`'s Foundation bridge.**

`(?s)` at the start of the pattern isn't always honored — multi-line `<style>` blocks (the common case in Anki note templates) will likely survive this strip and leak raw CSS into the watch UI.

Use the explicit option instead:

```swift
let pattern = try! NSRegularExpression(
    pattern: "<style.*?>.*?</style>",
    options: [.dotMatchesLineSeparators, .caseInsensitive]
)
```

Or, since the other regexes here have the same problem (`<[^>]+>` with newlines, the multi-newline collapse), build them once at file scope with explicit options rather than as inline string patterns. Worth a unit test against a representative Anki card HTML — that'd catch this immediately.

File: AmgiApp/Sources/Watch/WatchApp.swift [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+import Foundation
+import Sharing
+import SwiftUI
+import AmgiTheme
+
+@main
+struct WatchApp: App {
+    @State private var isLoggedIn = KeychainHelper.loadHostKey() != nil
+    init() {
+        try! prepareDependencies {
```
Comment (antigluten) [inline AmgiApp/Sources/Watch/WatchApp.swift]: **`try!` on launch is especially user-hostile on watchOS.**

Any failure here (backend init, directory creation, `openCollection` on a corrupted file) crashes on launch. watchOS will throttle relaunches aggressively, leaving the user with a watch app that just refuses to open with no recoverable signal.

Catch and present a minimal error view — at the very least something that shows the error string and offers "Sign out" so they can recover without reinstalling. This matters more on watch than on iOS because the user has fewer recovery affordances.

File: AmgiApp/project.yml [hunk 7]
```diff
@@ -3,11 +3,14 @@ options:
...
   deploymentTarget:
     iOS: "18.0"
+    watchOS: "11.0"
   defaultSourceDirectoryType: syncedFolder
 settings:
   base:
     SWIFT_VERSION: "6.0"
     SWIFT_STRICT_CONCURRENCY: complete
+    ONLY_ACTIVE_ARCH: true
+    ARCHS: arm64
```
Comment (antigluten) [inline AmgiApp/project.yml]: **These belong on the watch target, not at project base.**

`settings.base:` applies to **every target, every configuration**. Two concrete problems:

- `ONLY_ACTIVE_ARCH: true` for Release breaks `xcodebuild archive` / TestFlight distribution — archives must include all required slices.
- `ARCHS: arm64` excludes `x86_64` simulator builds, so anyone still on an Intel Mac can't even run the iOS simulator.

If this was added to fix a watchOS-specific build issue, scope it into the `AmgiWatchApp.settings.base:` block instead. Project base should stay platform-neutral.

File: AmgiApp/AmgiWatchApp.entitlements [hunk 8]
```diff
@@ -0,0 +1,10 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<plist version="1.0">
+<dict>
+    <key>com.apple.security.application-groups</key>
+    <array>
+        <string>group.com.amgiapp</string>
```
Comment (antigluten) [inline AmgiApp/AmgiWatchApp.entitlements]: App-group `group.com.amgiapp` is declared only on the watch side in this PR. I don't see a matching change to the iOS app or widget entitlements. If the intent is to share state (collection, prefs) between iPhone and Watch, the iOS app + widget extension both need the same group entry — otherwise this is just declaring an unshared group on one side and the sharing will silently fail.

If sharing isn't intended yet, consider removing the entitlement until it's wired up to avoid claiming capability you don't use.

**Review by antigluten — CHANGES_REQUESTED** [review]
## Review summary

Adds an `AmgiWatchApp` watchOS target (watchOS 11.0+) with login, deck list, deck detail, review, and stats screens. Extends `AnkiBridge` + `AmgiUI` to support `watchOS(.v10)`, teaches `build-xcframework.sh` to build `aarch64-apple-watchos` slices, and reorganises the iOS target so `Sources/Shared`, `Sources/Decks`, `Sources/Review`, `Sources/Stats` can be selectively shared with the Watch target. ~1.1k LOC added (≈700 of which is pbxproj churn from xcodegen).

### Blocking issues (inline)

1. **`scripts/build-xcframework.sh`** — `aarch64-apple-watchos*` are Tier 3 Rust targets; plain `cargo build` will fail without nightly + `-Z build-std`.
2. **`WatchDeckDetailView.swift:35`** — `.fullScreenCover` is iOS/tvOS only; needs `NavigationLink`/`.sheet` on watchOS.
3. **`WatchReviewView.swift:72`** — `AVAudioSession` is never configured; audio will likely be silent on hardware.
4. **`WatchReviewView.swift:45-46`** — Stacked single + double `onTapGesture` on the same view; ambiguous dispatch + delayed single tap.
5. **`WatchReviewView.swift:88`** — Inline `(?s)` modifier unreliable through Foundation; multi-line `<style>` blocks will leak CSS.
6. **`WatchApp.swift:13`** — `try!` on launch crashes irrecoverably on watchOS.
7. **`project.yml:12-13`** — `ONLY_ACTIVE_ARCH=true` and `ARCHS=arm64` at project base break archives and exclude Intel-Mac simulator builds.
8. **`AmgiWatchApp.entitlements`** — Watch declares an app group the iOS side doesn't share.

### Other observations (not inlined to keep the diff readable)

- **Stats sources hand-enumerated**: `AmgiWatchApp.sources` lists `Sources/Stats/*.swift` file by file — new charts on the iOS side won't reach the watch. Either include the folder with explicit excludes (the pattern used for `Decks`/`Review`), or document this as intentional.
- **`WatchThemeCompatibility.amgiCard(elevated:)`** — `elevated:` parameter is unused; thread it through or drop it.
- **Two-button rating UI** — `WatchReviewView` exposes only `.again` and `.good`. Acceptable simplification but it silently changes the FSRS rating distribution from the watch — worth documenting as design intent or exposing `.hard`/`.easy` behind the digital crown.
- **`_statusBarHidden()`** is an underscored SwiftUI API — fragile across watchOS versions. `toolbar(.hidden)` is the supported path.
- **No tests added** — `stripped` regex, `playAudio` URL extraction, and the deck-tree flatten/expand are all testable in isolation. One round-trip test for `stripped` against representative Anki HTML would have caught #5.
- **`print(...)` debug logging** in `WatchLoginView` and `WatchDeckListView` — replace with `Logger`/`os_log` before shipping.
- **`@State` declared after `body`** in `WatchDeckListView` — cosmetic, but the rest of the codebase puts state at the top.

### Security

Nothing alarming. Credentials still go through `KeychainHelper`, no new network endpoints. The unused app group is the only "ambient authority" concern.

### Recommendation

**Request changes.** The structure is reasonable and the platform-share approach via xcodegen excludes is the right shape — but items 1-3 in particular need resolving before this can build/run on real watch hardware for the next contributor.

---

*Reviewed by [Claude Code](https://claude.com/claude-code) — model: `claude-opus-4-7` (Opus 4.7, 1M context).*

**Comment by antigluten** [comment]
Hey @leaferiksen — first off, sorry for the slow response on this, it's been on my plate longer than it should have. Thank you so much for putting this together.

Heads up that the inline comments above were generated by Claude — I haven't gone through them line by line yet. My plan is to review what Claude suggests, only run the changes I actually agree with, and test on real hardware before pushing anything. So treat the inline notes as a starting point, not a final verdict from me.

I'm very happy to help carry this over the line — I can pick up some of the suggestions myself and push changes to your branch if that's easier for you, and I'll test on hardware too. Just let me know what you'd prefer: do you want to take a pass at the inline points yourself, or would it help if I push fixes for some/all of them and you review? Either way works for me.

Thanks again for the patience and the work — really excited to ship this. 🙏

**Comment by leaferiksen** [comment]
@antigluten Thanks for the feedback! I am right in the middle of my university's finals, so who handles this depends entirely on how soon you want this merged. I am happy to learn from this feedback and make the fixes, but you could probably do it much faster, and I would not mind if you wanted to do the finishing touches.

File: scripts/build-xcframework.sh (hunk 1 above)
Comment (leaferiksen) [reply scripts/build-xcframework.sh]: Opus is working off of outdated information, because the link they included says watchOS is tier 2. Leaving this unchanged.

File: AmgiApp/Sources/Watch/WatchReviewView.swift (hunk 4 above)
Comment (leaferiksen) [reply AmgiApp/Sources/Watch/WatchReviewView.swift:46]: I get the theory behind this critique, but I can't replicate the issue myself. I can't perceive the speed difference when removing the double tap, and the Digital Crown is occupied doing all the normal Digital Crown things (scrolling, Siri, Home button). We can re-add the back button if you don't like this system, but this feels really natural to me, and saves a lot of vertical screen space for potentially long cards.

Also, it could be playing different audio on the two sides of the card, or in my case, nothing at all on the first side, so it is not necessarily replaying the same audio. It should match behavior in other clients, so please tell me if it doesn't on your devices.

File: AmgiApp/Sources/Watch/WatchReviewView.swift (hunk 5 above)
Comment (leaferiksen) [reply AmgiApp/Sources/Watch/WatchReviewView.swift:100]: I have multiline styles on my cards and they don't cause any issues with the regex, but a coding agent wrote this part to my specifications as I am not familiar with regex, so I'll trust you that something isn't right here. Feel free to change this as you see to be necessary.

File: AmgiApp/project.yml (hunk 7 above)
Comment (leaferiksen) [reply AmgiApp/project.yml]: This was for a build issue, but whatever the issue was, it is long-gone. code removed

File: AmgiApp/AmgiWatchApp.entitlements (hunk 8 above)
Comment (leaferiksen) [reply AmgiApp/AmgiWatchApp.entitlements]: this was enough to make the iPhone + Apple Watch combo simulator work, but that isn't really important to the development of a standalone watch client, so I can probably just remove it for simplicity's sake.

**Comment by leaferiksen** [comment]
Hey @antigluten! I finally got around to fixing this up. Fixes for all the _Blocking issues_ that I know how to handle were provided in new commits. The _Other observations_ have not received work yet, but I'll plan to get to that part soon. 

My apologies for the increased number of file changes. It is the result of a whole bunch of autogenerated files changing now that I am building this from macOS and Xcode 27 betas. It should still build on 26 stable releases, since I am still using older 26.5 simulators, and targeting the same minimum versions.

I hope you are having a good summer☀️

**Comment by leaferiksen** [comment]
> • WatchThemeCompatibility.amgiCard(elevated:) — elevated: parameter is unused; thread it through or drop it.

This was intentional, but it may be the wrong way to do this (an LLM came up with it, I thought it looked ok). The elevated effect is fun on the phone, but there is no horizontal space for such an effect on the watch. Dropping the parameter makes the build fail with the following error: `TodayStatsCard.swift:113:29 Argument passed to call that takes no arguments` and threading it through (which I would guess means making the parameter do something beyond nullifying identical parameters in stat cards) is not my goal.

**Comment by leaferiksen** [comment]
`_statusBarHidden()` is used to hide the clock, which overlaps with card text. if we throw that out, we should throw out `.toolbar(.hidden, for: .navigationBar)`, `.ignoresSafeArea(edges: .top)` and `.onTapGesture(count: 2) { dismiss() }` as well. This is an change I could be fine with, although some screen space will be lost. I just want to be clear that it should be done all at once, if done at all.

**Comment by leaferiksen** [comment]
@antigluten I believe that the only thing left is tests and branch conflict resolution. I have never done either before, so could I now take you up on your offer to "carry this over the line", as you so generously offered months ago?

**Comment by antigluten** [comment]
Hey @leaferiksen — sorry for dropping off this for a couple of months. I've
picked it back up and finished the branch: it's caught up with `main` and the
conflicts are sorted. I'll get it merged. Thanks for your patience 🙏
